/// <reference path="../../../NovaBurst.ModularTypeScript.Core.UI/modules/Core/ref.ts" />
/// <reference path="../../../NovaBurst.ModularTypeScript.AppX.Core.UI/modules/AppX.Core/ref.ts" />
/// <reference path="../../../NovaBurst.ModularTypeScript.Core.UI/scripts/typings/angularjs/angular.d.ts" />
/// <reference path="module.angular.ts" />
/// <reference path="models/Customer.ts" />
/// <reference path="models/CustomerFilter.ts" />
/// <reference path="interfaces/ICustomerService.ts" />
/// <reference path="services/CustomerService.ts" />
//# sourceMappingURL=ref.js.map
